apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "###ZARF_CONST_NAME###"
  namespace: bigbang
spec:
  targetNamespace: "###ZARF_CONST_NAMESPACE###"
  interval: 10m
  chart:
    spec:
      chart: "###ZARF_CONST_PATH###"
      sourceRef:
        kind: GitRepository
        name: "###ZARF_CONST_NAME###"
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  values:
    istio:
      enabled: "###ZARF_VAR_ISTIO_ENABLED###"
    monitoring:
      enabled: "###ZARF_VAR_MONITORING_ENABLED###"
  valuesFrom:   
    - kind: Secret
      name: "bigbang-###ZARF_CONST_NAME###-values"
